PN-7497: conservation tracker lambda configuration
pagopa/pn-cn pull request #61
Opened 2024-09-02 09:34 UTC by ViVeniero

2024-09-04 14:57 UTC, fdammassa requested changes

2024-09-04 14:57 UTC, fdammassa commented on functions/legalConservationTracker/src/app/eventHandler.js
> +                batchItemFailures: [{ itemIdentifier: record.kinesisSeqNumber }],
@ViVeniero devi fermarti per forza al primo elemento fallito? perché essendo una sequenza non ha senso andare avanti?

2024-09-04 14:57 UTC, fdammassa commented on functions/legalConservationTracker/src/app/eventProcessor.js
> +    let lc_external_id = event.serviceProvider ? `${event.serviceProvider}` : `COMDATA::`
@ViVeniero qui c'è un errore; stai inserendo solo serviceProvider.

Inoltre il separatore non è incluso dentro `event.serviceProvider`

2024-09-04 14:57 UTC, fdammassa commented on functions/legalConservationTracker/src/app/eventProcessor.js
> +        throw new Error(`Legal Conservation error failed for fileKey ${fileKey}`)
@ViVeniero se c'è un evento di errore lo puoi skippare senza andare in errore

2024-09-04 14:57 UTC, fdammassa commented on functions/legalConservationTracker/src/app/eventProcessor.js
> +            throw new Error(`Problem to update tags for fileKey ${fileKey}`)
@ViVeniero aggiungi la response nell'Error

2024-09-04 14:57 UTC, fdammassa commented on scripts/aws/cfn/microservice.yml
> +      Timeout: 10
@ViVeniero portiamo a 180

2024-09-04 15:06 UTC, ViVeniero commented on functions/legalConservationTracker/src/app/eventHandler.js
> +                batchItemFailures: [{ itemIdentifier: record.kinesisSeqNumber }],
si essendo un kinesis stream

2024-09-04 15:06 UTC, ViVeniero commented on functions/legalConservationTracker/src/app/eventProcessor.js
> +    let lc_external_id = event.serviceProvider ? `${event.serviceProvider}` : `COMDATA::`
errore mio

2024-09-04 15:51 UTC, fdammassa approved these changes

2024-10-04 07:11 UTC, fdammassa requested changes

2024-10-04 07:11 UTC, fdammassa commented on functions/legalConservationTracker/src/app/safeStorageClient.js
> +    console.log('Content Type', contentType)
@ViVeniero togli questa loggata

2024-10-04 07:23 UTC, fdammassa approved these changes

2024-10-04 07:33 UTC, merged